### ISSUE TITLE
Standup 8/21/20

### ISSUE THREAD

**Issue by nicoleremy95** [zackdeacon/planit-backend#47]
**TODO**

- [x] create alert (something similar to show wrong password) NICOLE
- [x] Have an admin feature to add more users located on the user page (your map carousel) VINNY (front) & DEREK (back)
- [x] Add animations VINNY
- [x] Add function to move maps (user created, user as a guest, pending invitation) DEREK
- [ ] Email final render to guests (create button at bottom of Final Render page to activate send) ZACK
- [x] Make hover over feature on carousel VINNY
- [x] Create SIMPLE 404 page ZACK
- [x] render suggestion comments on modal NICOLE & BRYCE
- [x] style suggestion comments on modal VINNY
- [x] add a message confirm for delete functionality NICOLE
- [x] add tooltips for hover over buttons UI NICOLE 
- [x] Fix title link in Final Render Page (should go back to dashboard) BRYCE
- [x] Add validators in login form (user not found) NICOLE
- [x] Fix link to external link that sits in suggestion cards ZACK
- [ ] Debugging pages (backgrounds, responsiveness, etc.) VINNY  >> FINISHED/PENDING TEAM CONFIRMATION 
   - [ ] Clean up css code (delete commented code) and add titles to css files after debugging/responsiveness confirmed by team VINNY

**MDPs**
- [x] Add custom/additional categories on your map
- [ ] move past trips to a past trip section
- [x] split cost modal on final render page 
- [x] split cost and email final render to guests (for end of trip)
- [ ] maps ratings 
- [ ] offer trip suggestions based on previous maps 
- [ ] email based password recovery
- [ ] notification bell in nav

**SUNDAY**
- [ ] Group meeting 12:30pm

**SUNDAY NIGHT**
- [ ] Final Pres. Slides, Zoom Background, & ReadMe VINNY 

**MONDAY MORNING**

- [ ] Clean up console log DEREK
- [ ] Clean up react warnings VINNY
- [ ] Stage/Prepare a User/Account for demo-ing TEAM

**MONDAY AFTERNOON**
- [ ] Final Presentation Practice TEAM 
- [ ] Final Deploy TEAM

**MONDAY EVENING**
- [ ] Potential presentation practice 

**TUESDAY** 
- Be in room at 9:45am
- Dress to impress!
