### ISSUE TITLE
Standup 8/24/2020

### ISSUE THREAD

**Issue by nicoleremy95** [zackdeacon/planit-backend#55]
**TODO**

- [ ] Email final render to guests (create button at bottom of Final Render page to activate send) ZACK
- [ ] Debugging pages (backgrounds, responsiveness, etc.) VINNY  >> FINISHED/PENDING TEAM CONFIRMATION 
   - [ ] Clean up css code (delete commented code) and add titles to css files after debugging/responsiveness confirmed by team VINNY

**MDPs**
- [ ] move past trips to a past trip section
- [ ] maps ratings 
- [ ] offer trip suggestions based on previous maps 
- [ ] email based password recovery
- [ ] notification bell in nav

**SUNDAY**
- [ ] Group meeting 12:30pm

**MONDAY MORNING**
- [ ] Final Pres. Slides, Zoom Background, & ReadMe VINNY 
- [ ] Clean up console log DEREK
- [ ] Clean up react warnings VINNY
- [ ] Stage/Prepare a User/Account for demo-ing TEAM

**MONDAY AFTERNOON**
- [ ] Final Presentation Practice TEAM 
- [ ] Final Deploy TEAM

**MONDAY EVENING**
- [ ] Potential presentation practice 

**TUESDAY** 
- Be in room at 9:45am
- Dress to impress!
